ROLE_ADMIN = "admin"
ROLE_WAITER = "waiter"
ROLE_COOK = "cook"

ACTIVE_STATUS = "active"
INACTIVE_STATUS = "inactive"
DELETED_STATUS = "deleted"

ORDER_NEW = "new"
ORDER_IN_PROGRESS = "in_progress"
ORDER_PARTIALLY_READY = "partially_ready"
ORDER_READY = "ready"
ORDER_COMPLETED = "completed"
ORDER_CANCELLED = "cancelled"

ITEM_PENDING = "pending"
ITEM_READY = "ready"
ITEM_CANCELLED = "cancelled"

ALL_ROLES = {ROLE_ADMIN, ROLE_WAITER, ROLE_COOK}
ACTIVE_USER_STATUSES = {ACTIVE_STATUS}
DONE_ORDER_STATUSES = {ORDER_READY, ORDER_COMPLETED}
OPEN_ORDER_STATUSES = {ORDER_NEW, ORDER_IN_PROGRESS, ORDER_PARTIALLY_READY}
